# Generated by Django 4.1.7 on 2023-03-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('symbol_name', models.CharField(max_length=10, unique=True)),
                ('dividend_yield', models.DecimalField(decimal_places=2, max_digits=2, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('market_cap', models.PositiveBigIntegerField()),
            ],
        ),
    ]
