# Generated by Django 4.1.7 on 2023-03-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingCore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='dividend_yield',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
    ]
