# Generated by Django 4.1.7 on 2023-03-13 01:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tradingCore.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tradingCore', '0002_alter_stock_dividend_yield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Futures',
            fields=[
                ('symbol_name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('expiration_date', models.DateField()),
                ('margin_requirement', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)])),
                ('tick_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tick_size', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('net_p_and_l', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('mail', models.EmailField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='stock',
            name='id',
        ),
        migrations.AlterField(
            model_name='stock',
            name='dividend_yield',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol_name',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[tradingCore.validators.GreaterThanValidator(0)])),
                ('type', models.CharField(choices=[('deposit', 'deposit'), ('withdrawal', 'withdrawal')], max_length=10)),
                ('trader', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='tradingCore.trader')),
            ],
        ),
    ]
