# Generated by Django 4.1.7 on 2023-03-20 00:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradingCore', '0004_alter_transaction_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraderOwnedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradingCore.stock')),
                ('trader_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradingCore.trader')),
            ],
        ),
        migrations.AddConstraint(
            model_name='traderownedstock',
            constraint=models.UniqueConstraint(fields=('trader_id', 'stock_symbol'), name='unique_trader_stock'),
        ),
    ]
