# Generated by Django 4.1.7 on 2023-03-20 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradingCore', '0005_traderownedstock_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Futures',
        ),
    ]
