# Generated by Django 4.1.7 on 2023-03-20 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradingCore', '0007_alter_transaction_trader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='trader',
            new_name='trader_id',
        ),
    ]
